import type { ComponentCategory } from "../../../src/types.js";

export interface ManufacturerConfig {
  id: string;                      // e.g. "sennheiser"
  name: string;                    // "Sennheiser"
  categories: ComponentCategory[];  // which categories this brand covers
  listingUrls: string[];           // product category listing pages to crawl
  productLinkPattern: string;      // regex pattern to identify product page URLs
  needsPlaywright: boolean;        // true = JS-heavy site, false = static HTML
  rateLimit: number;               // ms between requests (be polite)
}

export const MANUFACTURERS: ManufacturerConfig[] = [
  // DACs
  {
    id: "topping",
    name: "Topping",
    categories: ["dac", "headphone_amp"],
    listingUrls: [
      "https://www.toppingaudio.com/collections/dac",
      "https://www.toppingaudio.com/collections/headphone-amp",
    ],
    productLinkPattern: "/products/",
    needsPlaywright: true,
    rateLimit: 2000,
  },
  {
    id: "schiit",
    name: "Schiit Audio",
    categories: ["dac", "headphone_amp", "preamp", "power_amp"],
    listingUrls: [
      "https://www.schiit.com/products/dacs",
      "https://www.schiit.com/products/headphone-amplifiers",
      "https://www.schiit.com/products/preamps",
      "https://www.schiit.com/products/stereo-amplifiers",
    ],
    productLinkPattern: "/products/",
    needsPlaywright: false,
    rateLimit: 2000,
  },
  {
    id: "rme",
    name: "RME",
    categories: ["dac"],
    listingUrls: ["https://www.rme-audio.de/hifi.html"],
    productLinkPattern: "rme-audio.de/",
    needsPlaywright: true,
    rateLimit: 2000,
  },
  {
    id: "ifi",
    name: "iFi Audio",
    categories: ["dac", "headphone_amp"],
    listingUrls: [
      "https://ifi-audio.com/collections/dac",
      "https://ifi-audio.com/collections/headphone-amps",
    ],
    productLinkPattern: "/products/",
    needsPlaywright: true,
    rateLimit: 2500,
  },
  {
    id: "cambridge",
    name: "Cambridge Audio",
    categories: ["dac", "preamp", "power_amp", "integrated", "source"],
    listingUrls: [
      "https://www.cambridgeaudio.com/usa/en/categories/dacs",
      "https://www.cambridgeaudio.com/usa/en/categories/amplifiers",
      "https://www.cambridgeaudio.com/usa/en/categories/streamers-and-network-players",
    ],
    productLinkPattern: "/products/",
    needsPlaywright: true,
    rateLimit: 2000,
  },
  {
    id: "benchmark",
    name: "Benchmark Media",
    categories: ["dac", "headphone_amp", "preamp", "power_amp"],
    listingUrls: ["https://benchmarkmedia.com/collections/all"],
    productLinkPattern: "benchmarkmedia.com/products/",
    needsPlaywright: false,
    rateLimit: 2000,
  },
  {
    id: "chord",
    name: "Chord Electronics",
    categories: ["dac", "headphone_amp"],
    listingUrls: [
      "https://www.chordelectronics.co.uk/product-category/dacs/",
      "https://www.chordelectronics.co.uk/product-category/headphone-amplifiers/",
    ],
    productLinkPattern: "/product/",
    needsPlaywright: true,
    rateLimit: 3000,
  },
  {
    id: "smsl",
    name: "SMSL",
    categories: ["dac", "headphone_amp", "power_amp"],
    listingUrls: ["https://www.smsl-audio.com/"],
    productLinkPattern: "/product/",
    needsPlaywright: true,
    rateLimit: 2000,
  },
  // Headphone Amps
  {
    id: "jds-labs",
    name: "JDS Labs",
    categories: ["headphone_amp", "dac"],
    listingUrls: ["https://jdslabs.com/shop/"],
    productLinkPattern: "jdslabs.com/product/",
    needsPlaywright: true,
    rateLimit: 2000,
  },
  {
    id: "burson",
    name: "Burson Audio",
    categories: ["headphone_amp", "integrated"],
    listingUrls: ["https://bursonaudio.com/products/"],
    productLinkPattern: "/products/",
    needsPlaywright: true,
    rateLimit: 2500,
  },
  // Headphones
  {
    id: "sennheiser",
    name: "Sennheiser",
    categories: ["headphone"],
    listingUrls: [
      "https://www.sennheiser.com/en-us/catalog/products/headphones/over-ear",
    ],
    productLinkPattern: "/catalog/products/headphones/",
    needsPlaywright: true,
    rateLimit: 2000,
  },
  {
    id: "beyerdynamic",
    name: "Beyerdynamic",
    categories: ["headphone"],
    listingUrls: ["https://north-america.beyerdynamic.com/headphones"],
    productLinkPattern: "/beyerdynamic/",
    needsPlaywright: true,
    rateLimit: 2000,
  },
  {
    id: "audeze",
    name: "Audeze",
    categories: ["headphone"],
    listingUrls: ["https://www.audeze.com/collections/headphones"],
    productLinkPattern: "/products/",
    needsPlaywright: false,
    rateLimit: 2000,
  },
  {
    id: "hifiman",
    name: "HiFiMAN",
    categories: ["headphone", "headphone_amp"],
    listingUrls: ["https://store.hifiman.com/collections/headphones"],
    productLinkPattern: "hifiman.com/products/",
    needsPlaywright: true,
    rateLimit: 2000,
  },
  {
    id: "focal",
    name: "Focal",
    categories: ["headphone", "speaker"],
    listingUrls: [
      "https://www.focal.com/en_US/headphones",
      "https://www.focal.com/en_US/hifi/hifi-loudspeakers",
    ],
    productLinkPattern: "/en_US/",
    needsPlaywright: true,
    rateLimit: 2500,
  },
  {
    id: "meze",
    name: "Meze Audio",
    categories: ["headphone"],
    listingUrls: ["https://mezeaudio.com/collections/headphones"],
    productLinkPattern: "/products/",
    needsPlaywright: false,
    rateLimit: 2000,
  },
  {
    id: "dan-clark",
    name: "Dan Clark Audio",
    categories: ["headphone"],
    listingUrls: ["https://danclarkaudio.com/headphones.html"],
    productLinkPattern: "danclarkaudio.com/",
    needsPlaywright: true,
    rateLimit: 2500,
  },
  {
    id: "zmf",
    name: "ZMF Headphones",
    categories: ["headphone"],
    listingUrls: ["https://www.zmfheadphones.com/headphones"],
    productLinkPattern: "zmfheadphones.com/headphones/",
    needsPlaywright: true,
    rateLimit: 3000,
  },
  {
    id: "akg",
    name: "AKG",
    categories: ["headphone"],
    listingUrls: ["https://www.akg.com/headphones"],
    productLinkPattern: "/headphones/",
    needsPlaywright: true,
    rateLimit: 2000,
  },
  // Power Amps / Integrated
  {
    id: "parasound",
    name: "Parasound",
    categories: ["power_amp", "integrated", "preamp"],
    listingUrls: [
      "https://parasound.com/amplifiers.php",
      "https://parasound.com/preamps.php",
    ],
    productLinkPattern: "parasound.com/products/",
    needsPlaywright: true,
    rateLimit: 2000,
  },
  {
    id: "nad",
    name: "NAD Electronics",
    categories: ["integrated", "power_amp", "preamp", "source"],
    listingUrls: [
      "https://nadelectronics.com/product-category/amplifiers/",
      "https://nadelectronics.com/product-category/digital-music-players/",
    ],
    productLinkPattern: "/product/",
    needsPlaywright: true,
    rateLimit: 2000,
  },
  {
    id: "emotiva",
    name: "Emotiva",
    categories: ["power_amp", "preamp", "integrated"],
    listingUrls: [
      "https://emotiva.com/collections/amplifiers",
      "https://emotiva.com/collections/preamplifiers",
    ],
    productLinkPattern: "/products/",
    needsPlaywright: false,
    rateLimit: 2000,
  },
  {
    id: "marantz",
    name: "Marantz",
    categories: ["integrated", "preamp", "source", "dac"],
    listingUrls: [
      "https://www.marantz.com/en-us/category/amplifiers",
      "https://www.marantz.com/en-us/category/network-audio",
    ],
    productLinkPattern: "marantz.com/en-us/product/",
    needsPlaywright: true,
    rateLimit: 2000,
  },
  {
    id: "rotel",
    name: "Rotel",
    categories: ["power_amp", "integrated", "preamp"],
    listingUrls: ["https://www.rotel.com/en-us/category/amplifiers"],
    productLinkPattern: "/product/",
    needsPlaywright: true,
    rateLimit: 2500,
  },
  {
    id: "hegel",
    name: "Hegel",
    categories: ["integrated", "preamp", "power_amp", "source"],
    listingUrls: ["https://www.hegel.com/en/products"],
    productLinkPattern: "hegel.com/en/products/",
    needsPlaywright: true,
    rateLimit: 2500,
  },
  // Speakers
  {
    id: "kef",
    name: "KEF",
    categories: ["speaker"],
    listingUrls: ["https://www.kef.com/en/collections/hi-fi-speakers"],
    productLinkPattern: "/en/products/",
    needsPlaywright: true,
    rateLimit: 2000,
  },
  {
    id: "klipsch",
    name: "Klipsch",
    categories: ["speaker"],
    listingUrls: [
      "https://www.klipsch.com/categories/floorstanding-speakers",
      "https://www.klipsch.com/categories/bookshelf-speakers",
    ],
    productLinkPattern: "klipsch.com/products/",
    needsPlaywright: false,
    rateLimit: 2000,
  },
  {
    id: "dynaudio",
    name: "Dynaudio",
    categories: ["speaker"],
    listingUrls: ["https://www.dynaudio.com/home-audio"],
    productLinkPattern: "dynaudio.com/",
    needsPlaywright: true,
    rateLimit: 2500,
  },
  {
    id: "monitor-audio",
    name: "Monitor Audio",
    categories: ["speaker"],
    listingUrls: ["https://www.monitoraudio.com/en/product-ranges/"],
    productLinkPattern: "monitoraudio.com/en/",
    needsPlaywright: true,
    rateLimit: 2500,
  },
  {
    id: "elac",
    name: "ELAC",
    categories: ["speaker"],
    listingUrls: ["https://www.elac.com/series/"],
    productLinkPattern: "elac.com/product/",
    needsPlaywright: true,
    rateLimit: 2000,
  },
  {
    id: "wharfedale",
    name: "Wharfedale",
    categories: ["speaker"],
    listingUrls: ["https://www.wharfedale.co.uk/collections/all"],
    productLinkPattern: "wharfedale.co.uk/products/",
    needsPlaywright: false,
    rateLimit: 2000,
  },
  // Preamps
  {
    id: "mcintosh",
    name: "McIntosh",
    categories: ["preamp", "power_amp", "integrated"],
    listingUrls: [
      "https://www.mcintoshlabs.com/products/preamplifiers",
      "https://www.mcintoshlabs.com/products/amplifiers",
    ],
    productLinkPattern: "mcintoshlabs.com/products/",
    needsPlaywright: true,
    rateLimit: 3000,
  },
  // Streamers / Sources
  {
    id: "bluesound",
    name: "Bluesound",
    categories: ["source"],
    listingUrls: ["https://www.bluesound.com/products/"],
    productLinkPattern: "bluesound.com/products/",
    needsPlaywright: true,
    rateLimit: 2000,
  },
  {
    id: "wiim",
    name: "WiiM",
    categories: ["source"],
    listingUrls: ["https://www.wiimhome.com/collections/all"],
    productLinkPattern: "/products/",
    needsPlaywright: true,
    rateLimit: 2000,
  },
  {
    id: "auralic",
    name: "Auralic",
    categories: ["source", "dac"],
    listingUrls: ["https://www.auralic.com/collections/all-products"],
    productLinkPattern: "/products/",
    needsPlaywright: true,
    rateLimit: 3000,
  },
];
